apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: valkey
    protocol: TCP
    name: valkey
  selector:
    {{- include "valkey.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: {{ .Values.service.port }}
    targetPort: valkey
    protocol: TCP
    name: valkey
  selector:
    {{- include "valkey.selectorLabels" . | nindent 4 }}