# .github/workflows/test-runner.yml
name: Test Self-Hosted Runner
on: workflow_dispatch

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Check Docker
      run: docker --version
      
    - name: Check Kind
      run: kind --version
      
    - name: Check Kubectl
      run: kubectl version --client
      
    - name: List Kind Clusters
      run: kind get clusters
